server:
  port: 8080

spring:
  application:
    name: keycloak-spring-demo

  rabbitmq:
    listener:
      simple:
        retry:
          enabled: true
          max-attempts: 5
          initial-interval: 5000

  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring.json.add.type.headers: false
    consumer:
      group-id: demo-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.demo.keycloak.messaging"

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://52.65.212.193:8180/realms/demo-realm
          jwk-set-uri: http://52.65.212.193:8180/realms/demo-realm/protocol/openid-connect/certs

      client:
        registration:
          keycloak:
            client-id: spring-demo-client
            client-secret: super-secret-client-key
            scope: openid, profile, email, roles
            authorization-grant-type: authorization_code
            redirect-uri: "http://52.65.212.193:8080/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: http://52.65.212.193:8180/realms/demo-realm
            user-name-attribute: preferred_username

app:
  keycloak:
    realm: demo-realm
    server-url: http://52.65.212.193:8180
    client-id: spring-demo-client

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

rabbitmq:
  exchange: demo.exchange
  queue: user.events.queue
  routing-key: user.event
  dead-letter-exchange: demo.dead-letter.exchange
  dead-letter-queue: user.events.dead-letter.queue
  dead-letter-routing-key: user.event.dead

kafka:
  topics:
    user-events: user-events
    user-events-dlt: user-events.DLT

logging:
  level:
    org.springframework.security: DEBUG
    com.demo.keycloak: DEBUG
